project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    mermaid: 
      theme: neutral
  apaquarto-html:
    toc: true
    comments:
      utterances:
        repo: kbmcgowan/play-manuscript
  apaquarto-docx: default

