on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

name: install google fonts
          
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          packages: fonts-sil-gentiumplus
          version: pre-release
          tinytex: true


      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
